# Generated by Django 3.0.9 on 2020-08-06 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailvideos', '0010_video_ordering'),
        ('base', '0004_auto_20180522_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='header_video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='wagtailvideos.Video'),
        ),
    ]
