# Generated by Django 3.0.9 on 2020-08-07 09:05

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_standardpage_header_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='body_rich',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
